update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :deploy do
    increment_build_number(xcodeproj: "mobileapp.xcodeproj")
    build_app(workspace: "TraceCov.xcworkspace", scheme: "TraceCov", xcargs: "-allowProvisioningUpdates")
    upload_to_testflight(skip_waiting_for_build_processing: true)
  end
end
